=== idhowardgj94/FinancialAlertSys/log/log.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Record (ConnectIP)>
<!ATTLIST Record
	Number CDATA "0"
>
<!ELEMENT ConnectIP (Page, UserID, Time)>
<!ELEMENT Page (#PCDATA)>
<!ELEMENT UserID (#PCDATA)>
<!ELEMENT Time (Date, Hour, Minute)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Hour (#PCDATA)>
<!ELEMENT Minute (#PCDATA)>

=== idhowardgj94/FinancialAlertSys/log/201608.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Record SYSTEM "log.dtd" >
<Record Number="0">
  <ConnectIP>
    <Page>Page</Page>
    <UserID>UserID</UserID>
    <Time>
      <Date>Date</Date>
      <Hour>Hour</Hour>
      <Minute>Minute</Minute>
    </Time>
  </ConnectIP>
</Record>
